### ISSUE TITLE
Configure MISP TI Platform 4th step & Unable to Connect to MISP Server

### ISSUE THREAD

**Issue by KaidoLogi** [Cyberlorians/Articles#7]
4th Step under Configure MISP TI Platform

**"After logging in, navigate to 'Sync Actions'>'List Feeds'. Select both default feeds, enable and cache. Once done, click 'Fetch and store all feed data'. These two are by default, you can add more from the proper MISP website [here](https://www.misp-project.org/feeds/)."**

I'm not quite understanding where to find 'Sync Actions'>'List Feeds', when logged into the ubuntu server using the misp account?

**Comment by KaidoLogi** [comment]
Closing as for some strange reason article initially didn't show a single image

**Comment by Cyberlorians** [comment]
Ah ok. You good?
________________________________

**Comment by KaidoLogi** [comment]
Thanks for the reply.

Yes and no. Regarding the previous problem managed to find a workaround, now the misp server isn't loading up when using the local host address.

Telnet'd on port 443 and it's open, pinged, no packet lost, and other sites are accessible.

Any suggestions?

![image](https://user-images.githubusercontent.com/119605448/209307203-5f44b19d-3e04-4081-a028-3bd5f59e53cc.png)
